// Top US makes by 2024 registrations. Used by detectInputShape to recognize
// a single-word make token. Add a make here when the search box should treat
// it as a make rather than a name.
export const KNOWN_MAKES = new Set<string>([
  'Acura',
  'Alfa Romeo',
  'Audi',
  'BMW',
  'Buick',
  'Cadillac',
  'Chevrolet',
  'Chrysler',
  'Dodge',
  'Fiat',
  'Ford',
  'Genesis',
  'GMC',
  'Honda',
  'Hyundai',
  'Infiniti',
  'Jaguar',
  'Jeep',
  'Kia',
  'Land Rover',
  'Lexus',
  'Lincoln',
  'Maserati',
  'Mazda',
  'Mercedes-Benz',
  'Mini',
  'Mitsubishi',
  'Nissan',
  'Polestar',
  'Pontiac',
  'Porsche',
  'RAM',
  'Rivian',
  'Saab',
  'Saturn',
  'Scion',
  'Smart',
  'Subaru',
  'Tesla',
  'Toyota',
  'Volkswagen',
  'Volvo',
])
